#!/usr/bin/env bash

set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${CORNERSTONE_POSTGRES_APP_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${CORNERSTONE_POSTGRES_APP_USER}', '${CORNERSTONE_POSTGRES_APP_PASSWORD}');
    END IF;
END
\$\$;

GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${CORNERSTONE_POSTGRES_APP_USER}";
GRANT ALL ON SCHEMA public TO "${CORNERSTONE_POSTGRES_APP_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "${CORNERSTONE_POSTGRES_APP_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "${CORNERSTONE_POSTGRES_APP_USER}";
SQL
